[package]
name = "application"
version = "0.1.0"
edition = "2024"
default-run = "kremlin"

[dependencies]
business = { path = "../business" }
entity = { path = "../entity" }
migration = { path = "../migration" }

#workspace dependecies
chrono = { workspace = true }
dotenvy = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-sqs = { workspace = true }


#module dependencies
axum = { version = "0.8.9", features = ["multipart"] }
anyhow = "1.0.104"
tower-http = { version = "0.7.0", features = ["full"] }
log = "0.4.33"
fluent-templates = "0.15.1"
unic-langid = { version = "0.9", features = ["macros"] }

[[bin]]
name = "kremlin"
path = "src/main.rs"
