import type { Product, ProductCategory, Coupon } from '../types';

export const MOCK_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat-1',
    name: 'Vinhos Tintos & Nobres',
    slug: 'vinhos-tintos',
    description: 'Rótulos selecionados de vinhedos históricos e safras especiais',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=600&auto=format&fit=crop',
    itemCount: 12,
  },
  {
    id: 'cat-2',
    name: 'Vinhos Brancos & Espumantes',
    slug: 'vinhos-brancos',
    description: 'Frescor, notas minerais e borbulhas elegantes para celebrar',
    imageUrl: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?q=80&w=600&auto=format&fit=crop',
    itemCount: 8,
  },
  {
    id: 'cat-3',
    name: 'Azeites & Especiarias',
    slug: 'azeites-especiarias',
    description: 'Azeites extravirgens premiados e temperos artesanais',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=600&auto=format&fit=crop',
    itemCount: 15,
  },
  {
    id: 'cat-4',
    name: 'Queijos & Charcutaria',
    slug: 'queijos-charcutaria',
    description: 'Cura tradicional, sabores intensos e harmonizações perfeitas',
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?q=80&w=600&auto=format&fit=crop',
    itemCount: 10,
  },
  {
    id: 'cat-5',
    name: 'Acessórios do Sommelier',
    slug: 'acessorios',
    description: 'Decanters de cristal, saca-rolhas profissionais e taças',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop',
    itemCount: 6,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    slug: 'chateau-detinets-reserva-2018',
    name: 'Château Detinets Gran Reserva 2018',
    subtitle: 'Envelhecido 24 meses em carvalho francês',
    description: 'Um vinho tinto encorpado de cor rubi profunda com reflexos violáceos. Apresenta aromas complexos de frutas negras maduras, cassis, notas de baunilha, tabaco e couro. Em boca é aveludado, com taninos finos e final persistente e memorável.',
    price: 349.90,
    originalPrice: 429.00,
    currency: 'BRL',
    category: 'Vinhos Tintos & Nobres',
    categorySlug: 'vinhos-tintos',
    thumbnail: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=800&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewCount: 48,
    stock: 15,
    isFeatured: true,
    isNew: true,
    tags: ['Premium', 'Safra Histórica', 'Gran Reserva'],
    attributes: {
      brand: 'Château Novgorod',
      origin: 'Bordeaux / Vale dos Vinhedos',
      year: 2018,
      weight: '750ml',
      sku: 'NVG-WINE-001',
    },
    variants: [
      { id: 'v-1-1', name: 'Garrafa Individual 750ml', sku: 'NVG-WINE-001-1', price: 349.90, stock: 15 },
      { id: 'v-1-2', name: 'Caixa de Madeira (3 un)', sku: 'NVG-WINE-001-3', price: 989.90, originalPrice: 1049.70, stock: 4 },
    ],
  },
  {
    id: 'prod-2',
    slug: 'volkhov-sauvignon-blanc-reserva',
    name: 'Volkhov Sauvignon Blanc Reserva',
    subtitle: 'Acidez refrescante com notas cítricas e maracujá',
    description: 'Vinho branco leve e aromático, colhido nas brisas frescas do Vale do Rio Volkhov. Notas vívidas de maracujá, lima da pérsia e toque mineral cristalino.',
    price: 189.00,
    originalPrice: 220.00,
    currency: 'BRL',
    category: 'Vinhos Brancos & Espumantes',
    categorySlug: 'vinhos-brancos',
    thumbnail: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?q=80&w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?q=80&w=800&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 32,
    stock: 24,
    isFeatured: true,
    isNew: false,
    tags: ['Branco', 'Cítrico', 'Vinho de Verão'],
    attributes: {
      brand: 'Volkhov Estates',
      origin: 'Marlborough & Serra Gaúcha',
      year: 2022,
      weight: '750ml',
      sku: 'NVG-WINE-002',
    },
  },
  {
    id: 'prod-3',
    slug: 'azeite-extravirgem-koroneiki-monovarietal',
    name: 'Azeite Extravirgem Koroneiki Monovarietal',
    subtitle: 'Acidez máxima 0.15% — Extração a frio imediata',
    description: 'Azeite de oliva extravirgem de categoria superior obtido diretamente de azeitonas da variedade grega Koroneiki, prensadas a frio em até 4 horas após a colheita. Notas de ervas frescas e toque picante no palato.',
    price: 119.50,
    currency: 'BRL',
    category: 'Azeites & Especiarias',
    categorySlug: 'azeites-especiarias',
    thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=800&auto=format&fit=crop',
    ],
    rating: 4.95,
    reviewCount: 64,
    stock: 35,
    isFeatured: true,
    isNew: true,
    tags: ['Azeite de Oliva', 'Prensado a Frio', 'Acidez 0.15%'],
    attributes: {
      brand: 'Torg Gastronomia',
      origin: 'Peloponeso & Rio Grande do Sul',
      weight: '500ml',
      sku: 'NVG-OIL-003',
    },
  },
  {
    id: 'prod-4',
    slug: 'queijo-artesanal-maturado-caverna',
    name: 'Queijo Artesanal Canastra Reserva 12 Meses',
    subtitle: 'Maturado em caverna subterrânea com mofo branco natural',
    description: 'Produzido com leite cru de vacas alimentadas em pastagens nativas. O processo de cura lenta de 12 meses confere textura quebradiça, cristais de tirosina crocantes e sabor umami inigualável.',
    price: 145.00,
    originalPrice: 165.00,
    currency: 'BRL',
    category: 'Queijos & Charcutaria',
    categorySlug: 'queijos-charcutaria',
    thumbnail: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?q=80&w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1452195100486-9cc805987862?q=80&w=800&auto=format&fit=crop',
    ],
    rating: 5.0,
    reviewCount: 52,
    stock: 10,
    isFeatured: true,
    tags: ['Artesanal', 'Cura 12 Meses', 'Premiado'],
    attributes: {
      brand: 'Queijaria Ilmen',
      origin: 'Serra da Canastra, MG',
      weight: '600g',
      sku: 'NVG-CHS-004',
    },
  },
  {
    id: 'prod-5',
    slug: 'decanter-cristal-soprado-artesanal',
    name: 'Decanter de Cristal de Chumbo Soprado à Mão',
    subtitle: 'Capacidade 1500ml — Formato ergonômico anti-gotas',
    description: 'Peça nobre de cristal soprado artesanalmente, desenhada para acelerar a aeração de vinhos estruturados e reter sedimentos de safras de guarda. Design escultural digno de uma mesa imperial.',
    price: 289.90,
    originalPrice: 350.00,
    currency: 'BRL',
    category: 'Acessórios do Sommelier',
    categorySlug: 'acessorios',
    thumbnail: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewCount: 19,
    stock: 8,
    isFeatured: false,
    tags: ['Cristal', 'Soprado à mão', 'Acessórios'],
    attributes: {
      brand: 'Veche Sommelier Line',
      origin: 'Boêmia, República Tcheca',
      weight: '850g',
      sku: 'NVG-ACC-005',
    },
  },
  {
    id: 'prod-6',
    slug: 'presunto-iberico-bellota-fatiado-100g',
    name: 'Jamón Ibérico 100% Bellota Fatiado 100g',
    subtitle: 'Cura de 48 meses — Porcos criados livres em dehesas',
    description: 'O ápice da charcutaria mundial. Fatias translúcidas entremeadas por gordura nobre que derrete à temperatura corporal, liberando notas adocicadas de nozes e avelãs.',
    price: 195.00,
    currency: 'BRL',
    category: 'Queijos & Charcutaria',
    categorySlug: 'queijos-charcutaria',
    thumbnail: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewCount: 28,
    stock: 18,
    isFeatured: false,
    isNew: true,
    tags: ['Pata Negra', 'Bellota', 'Cura 48M'],
    attributes: {
      brand: 'Jabugo Imperial',
      origin: 'Huelva, Espanha',
      weight: '100g',
      sku: 'NVG-JAM-006',
    },
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    code: 'TORG10',
    discountType: 'percentage',
    discountValue: 10,
    description: '10% de desconto na primeira compra no mercado Torg',
    minimumAmount: 100,
  },
  {
    code: 'NOVGOROD50',
    discountType: 'fixed',
    discountValue: 50,
    description: 'R$ 50 OFF em pedidos acima de R$ 300',
    minimumAmount: 300,
  },
];
