[package]
name = "migration"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { workspace = true }
uuid = { workspace = true }

[dependencies.sea-orm-migration]
version = "2.0.3"
features = ["runtime-tokio-rustls", "sqlx-mysql", "with-chrono"]
