import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Pencil, Plus, RefreshCw } from "lucide-react";
import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import PageMeta from "@/components/common/PageMeta";
import ComponentCard from "@/components/common/ComponentCard";
import Button from "@/components/ui/button/Button";
import Badge from "@/components/ui/badge/Badge";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { fetchCategories, fetchProducts, fetchSkus } from "@/store/catalogSlice";
import { fetchTenants } from "@/store/tenantSlice";
import { ROLES } from "@/utils/enums";
import CatalogImportModal from "@/components/catalog/CatalogImportModal";
export default function CatalogList() {
  const { kind = "products" } = useParams(); const [importOpen, setImportOpen] = useState(false); const dispatch = useAppDispatch(); const state = useAppSelector((s) => s.catalog); const tenants = useAppSelector((s) => s.tenant.tenantsList); const user = useAppSelector((s) => s.auth.user); const sys = user?.role === ROLES.SYS_ADMIN; const tenantId = user?.tenantId ?? user?.tenant_id; const title = kind[0].toUpperCase() + kind.slice(1); const rows = kind === "categories" ? state.categories : kind === "skus" ? state.skus : state.products; const filtered = sys ? rows : rows.filter((r) => r.tenantId === tenantId); const load = () => { if (kind === "categories") dispatch(fetchCategories()); else if (kind === "skus") dispatch(fetchSkus()); else dispatch(fetchProducts()); }; useEffect(() => { load(); dispatch(fetchTenants()); }, [dispatch, kind]); const tenantName = (id?: number | null) => tenants.find((t) => t.id === id)?.businessName || tenants.find((t) => t.id === id)?.companyName || `#${id ?? "—"}`;
  return <><PageMeta title={`${title} | Veche`} description={`Manage ${title.toLowerCase()}`}/><PageBreadcrumb pageTitle={title}/><ComponentCard title={`${title} management`} desc={sys ? "Manage catalog data across all tenants." : "Manage catalog data for your tenant."}><div className="mb-5 flex justify-end gap-3"><Button variant="outline" startIcon={<RefreshCw size={16}/>} onClick={load}>Refresh</Button>{kind === "products" && <Button variant="outline" onClick={() => setImportOpen(true)}>Import CSV/XLSX</Button>}<Link to={`/catalog/${kind}/new`}><Button startIcon={<Plus size={16}/>}>Add {kind === "skus" ? "SKU" : kind.slice(0, -1)}</Button></Link></div>{state.error && <div className="mb-4 rounded-lg border border-error-200 bg-error-50 p-3 text-sm text-error-600">{state.error}</div>}{state.loading && filtered.length === 0 ? <div className="py-12 text-center text-gray-500">Loading…</div> : filtered.length === 0 ? <div className="py-12 text-center text-gray-500">No {title.toLowerCase()} found.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-gray-100 dark:border-gray-800"><th className="px-4 py-3">Name / code</th><th className="px-4 py-3">Details</th><th className="px-4 py-3">Tenant</th><th className="px-4 py-3">Status</th><th/></tr></thead><tbody>{filtered.map((r: any) => <tr key={r.id} className="border-b border-gray-100 dark:border-gray-800"><td className="px-4 py-4 font-medium">{r.name || r.code}</td><td className="px-4 py-4 text-gray-500">{kind === "skus" ? `${r.variantKey} · ${(r.priceCents / 100).toFixed(2)}` : r.slug || r.brand || "—"}</td><td className="px-4 py-4 text-gray-500">{tenantName(r.tenantId)}</td><td className="px-4 py-4"><Badge size="sm" color={r.active ? "success" : "light"}>{r.active ? "Active" : "Inactive"}</Badge></td><td className="px-4 py-4 text-right"><Link className="inline-flex items-center gap-1 text-brand-500" to={`/catalog/${kind}/${r.id}/edit`}><Pencil size={15}/>Edit</Link></td></tr>)}</tbody></table></div>}</ComponentCard>{importOpen && <CatalogImportModal onClose={() => setImportOpen(false)} onImported={() => { setImportOpen(false); load(); }}/>}</>;
}
