import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { catalogService, type Category, type CategoryInput, type Product, type ProductInput, type Sku, type SkuInput } from "@/services/catalogService";
import { getApiErrorMessage } from "@/services/api";
interface CatalogState { categories: Category[]; products: Product[]; skus: Sku[]; loading: boolean; error: string | null }
const initialState: CatalogState = { categories: [], products: [], skus: [], loading: false, error: null };
const fail = (e: unknown) => getApiErrorMessage(e, "Catalog request failed");
export const fetchCategories = createAsyncThunk<Category[], void, { rejectValue: string }>("catalog/fetchCategories", async (_, { rejectWithValue }) => { try { return await catalogService.categories(); } catch (e) { return rejectWithValue(fail(e)); } });
export const fetchProducts = createAsyncThunk<Product[], void, { rejectValue: string }>("catalog/fetchProducts", async (_, { rejectWithValue }) => { try { return await catalogService.products(); } catch (e) { return rejectWithValue(fail(e)); } });
export const fetchSkus = createAsyncThunk<Sku[], void, { rejectValue: string }>("catalog/fetchSkus", async (_, { rejectWithValue }) => { try { return await catalogService.skus(); } catch (e) { return rejectWithValue(fail(e)); } });
export const saveCategory = createAsyncThunk<Category, { id?: number; data: CategoryInput }, { rejectValue: string }>("catalog/saveCategory", async ({ id, data }, { rejectWithValue, dispatch }) => { try { const result = id ? await catalogService.updateCategory(id, data) : await catalogService.createCategory(data); dispatch(fetchCategories()); return result; } catch (e) { return rejectWithValue(fail(e)); } });
export const saveProduct = createAsyncThunk<Product, { id?: number; data: ProductInput }, { rejectValue: string }>("catalog/saveProduct", async ({ id, data }, { rejectWithValue, dispatch }) => { try { const result = id ? await catalogService.updateProduct(id, data) : await catalogService.createProduct(data); dispatch(fetchProducts()); return result; } catch (e) { return rejectWithValue(fail(e)); } });
export const saveSku = createAsyncThunk<Sku, { id?: number; data: SkuInput }, { rejectValue: string }>("catalog/saveSku", async ({ id, data }, { rejectWithValue, dispatch }) => { try { const result = id ? await catalogService.updateSku(id, data) : await catalogService.createSku(data); dispatch(fetchSkus()); return result; } catch (e) { return rejectWithValue(fail(e)); } });
const catalogSlice = createSlice({ name: "catalog", initialState, reducers: { clearCatalogError: (state) => { state.error = null; } }, extraReducers: (builder) => { for (const thunk of [fetchCategories, fetchProducts, fetchSkus]) builder.addCase(thunk.pending, (s) => { s.loading = true; s.error = null; }).addCase(thunk.rejected, (s, a) => { s.loading = false; s.error = a.payload || "Catalog request failed"; }); builder.addCase(fetchCategories.fulfilled, (s, a) => { s.loading = false; s.categories = a.payload; }).addCase(fetchProducts.fulfilled, (s, a) => { s.loading = false; s.products = a.payload; }).addCase(fetchSkus.fulfilled, (s, a) => { s.loading = false; s.skus = a.payload; }).addCase(saveCategory.fulfilled, (s) => { s.loading = false; }).addCase(saveProduct.fulfilled, (s) => { s.loading = false; }).addCase(saveSku.fulfilled, (s) => { s.loading = false; }).addCase(saveCategory.rejected, (s, a) => { s.loading = false; s.error = a.payload || "Unable to save category"; }).addCase(saveProduct.rejected, (s, a) => { s.loading = false; s.error = a.payload || "Unable to save product"; }).addCase(saveSku.rejected, (s, a) => { s.loading = false; s.error = a.payload || "Unable to save SKU"; }); } });
export const { clearCatalogError } = catalogSlice.actions;
export default catalogSlice.reducer;
