import { useMemo, useRef, useState } from "react";
import Papa from "papaparse";
import * as XLSX from "xlsx";
import { Upload, X } from "lucide-react";
import Button from "@/components/ui/button/Button";
import Input from "@/components/form/input/InputField";
import Label from "@/components/form/Label";
import { catalogService } from "@/services/catalogService";
import { useAppSelector } from "@/store/hooks";
import { ROLES } from "@/utils/enums";

type ImportRow = { product_key: string; sku_key: string; category_key: string; product_name: string; slug: string; description: string; brand: string; ncm: string; cest: string; origem_mercadoria: number; code: string; variant_key: string; price_cents: number; compare_at_price_cents: string; weight_g: number; width_mm: number; height_mm: number; length_mm: number; active: boolean; color: string };
const blank = (): ImportRow => ({ product_key: "", sku_key: "", category_key: "", product_name: "", slug: "", description: "", brand: "", ncm: "22042100", cest: "0301200", origem_mercadoria: 0, code: "", variant_key: "750ml", price_cents: 0, compare_at_price_cents: "", weight_g: 0, width_mm: 0, height_mm: 0, length_mm: 0, active: true, color: "" });
const flatWorkbook = (book: XLSX.WorkBook): ImportRow[] => { const read = (name: string) => book.Sheets[name] ? XLSX.utils.sheet_to_json<Record<string, unknown>>(book.Sheets[name], { defval: "" }) : []; const products = read("Products"); const skus = read("SKUs"); const links = read("ProductCategories"); const categories = new Map(read("Categories").map(row => [String(row.external_key), String(row.slug || row.external_key)])); const productMap = new Map(products.map(row => [String(row.external_key), row])); return skus.map(row => { const p = productMap.get(String(row.product_key)) || {}; const link = links.find(item => String(item.product_key) === String(row.product_key)); const result = blank(); Object.assign(result, { product_key: String(row.product_key), sku_key: String(row.external_key), category_key: categories.get(String(link?.category_key || "")) || "", product_name: String(p.name || ""), slug: String(p.slug || ""), description: String(p.description || ""), brand: String(p.brand || ""), ncm: String(p.ncm || "22042100"), cest: String(p.cest || "0301200"), origem_mercadoria: Number(p.origem_mercadoria || 0), code: String(row.code || ""), variant_key: String(row.variant_key || "750ml"), price_cents: Number(row.price_cents || 0), weight_g: Number(row.weight_g || 0), width_mm: Number(row.width_mm || 0), height_mm: Number(row.height_mm || 0), length_mm: Number(row.length_mm || 0) }); return result; }); };

export default function CatalogImportModal({ onClose, onImported }: { onClose: () => void; onImported: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [rows, setRows] = useState<ImportRow[]>([]); const [file, setFile] = useState<File | null>(null); const [tenantId, setTenantId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<{ total: number; created: number; updated: number; unchanged: number } | null>(null); const { user } = useAppSelector(s => s.auth); const tenants = useAppSelector(s => s.tenant.tenantsList); const isSysAdmin = user?.role === ROLES.SYS_ADMIN; const effectiveTenant = isSysAdmin ? Number(tenantId) : Number(user?.tenantId ?? user?.tenant_id ?? 0);
  const errors = useMemo(() => rows.flatMap((row, index) => [!row.product_name.trim() && `Row ${index + 1}: product name is required`, !row.slug.trim() && `Row ${index + 1}: slug is required`, !row.code.trim() && `Row ${index + 1}: SKU code is required`, row.price_cents < 0 && `Row ${index + 1}: price cannot be negative`].filter(Boolean) as string[]), [rows]);
  const parse = (selected: File) => { setFile(selected); setError(""); if (selected.name.toLowerCase().endsWith(".csv")) Papa.parse<ImportRow>(selected, { header: true, skipEmptyLines: true, complete: result => setRows(result.data.map(row => ({ ...blank(), ...row, price_cents: Number(row.price_cents), origem_mercadoria: Number(row.origem_mercadoria), weight_g: Number(row.weight_g), width_mm: Number(row.width_mm), height_mm: Number(row.height_mm), length_mm: Number(row.length_mm), active: String(row.active) !== "false" }))), error: e => setError(e.message) }); else selected.arrayBuffer().then(buffer => setRows(flatWorkbook(XLSX.read(buffer, { type: "array" })))).catch(e => setError(String(e))); };
  const update = (index: number, key: keyof ImportRow, value: string) => setRows(current => current.map((row, i) => i === index ? { ...row, [key]: ["price_cents", "weight_g", "width_mm", "height_mm", "length_mm"].includes(key) ? Number(value) : value } : row));
  const submit = async () => { if (!file || !effectiveTenant || errors.length || busy) return; setBusy(true); setError(""); try { setResult(await catalogService.importCatalog(file, effectiveTenant, rows)); onImported(); } catch (e: any) { setError(e?.response?.data?.message || "Import failed"); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-99999 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-7xl overflow-hidden rounded-xl bg-white p-6 dark:bg-gray-900"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Import wine catalog</h2><p className="text-sm text-gray-500">Upload CSV/XLSX, review every row, edit values, then import.</p></div><button onClick={onClose} aria-label="Close"><X/></button></div>{result ? <div className="space-y-4"><p>Imported {result.total} rows: {result.created} created, {result.updated} updated, {result.unchanged} unchanged.</p><Button onClick={onClose}>Close</Button></div> : <><div className="mb-4 flex flex-wrap items-end gap-4"><div><Label>Catalog file</Label><input ref={input} type="file" accept=".csv,.xlsx" onChange={e => e.target.files?.[0] && parse(e.target.files[0])}/></div>{isSysAdmin ? <div><Label>Target tenant</Label><select value={tenantId} onChange={e => setTenantId(e.target.value)} className="h-11 rounded-lg border px-3"><option value="">Select tenant</option>{tenants.map(t => <option key={t.id} value={t.id || ""}>{t.businessName || t.companyName}</option>)}</select></div> : null}<span className="text-sm text-gray-500">{file?.name || "No file selected"} · {rows.length} rows</span></div>{error && <p className="mb-3 rounded bg-error-50 p-3 text-error-600">{error}</p>}{errors.length > 0 && <p className="mb-3 rounded bg-warning-50 p-3 text-warning-700">{errors.length} validation errors. Fix them before importing.</p>}<div className="max-h-[55vh] overflow-auto"><table className="w-full min-w-[1100px] text-start text-xs"><thead><tr className="border-b"><th>#</th><th>Product</th><th>Slug</th><th>SKU code</th><th>Variant</th><th>Price cents</th><th>Category</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.sku_key}-${index}`} className="border-b"><td>{index + 1}</td><td><Input value={row.product_name} onChange={e => update(index, "product_name", e.target.value)}/></td><td><Input value={row.slug} onChange={e => update(index, "slug", e.target.value)}/></td><td><Input value={row.code} onChange={e => update(index, "code", e.target.value)}/></td><td><Input value={row.variant_key} onChange={e => update(index, "variant_key", e.target.value)}/></td><td><Input type="number" value={row.price_cents} onChange={e => update(index, "price_cents", e.target.value)}/></td><td>{row.category_key}</td></tr>)}</tbody></table></div><div className="mt-5 flex justify-end gap-3"><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!file || !effectiveTenant || errors.length > 0 || busy} startIcon={<Upload size={16}/>} onClick={submit}>{busy ? "Importing…" : "Import catalog"}</Button></div></>}</div></div>;
}
