//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "campaign_target"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub campaign_id: i64,
    pub target_type: String,
    pub target_id: i64,
    pub created_at: DateTime,
    pub created_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    CampaignId,
    TargetType,
    TargetId,
    CreatedAt,
    CreatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Campaign,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::CampaignId => ColumnType::Integer.def(),
            Self::TargetType => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TargetId => ColumnType::Integer.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Campaign => Entity::belongs_to(super::campaign_entity::Entity)
                .from((Column::TenantId, Column::CampaignId))
                .to((
                    super::campaign_entity::Column::TenantId,
                    super::campaign_entity::Column::Id,
                ))
                .into(),
        }
    }
}

impl Related<super::campaign_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Campaign.def()
    }
}

crate::impl_tenant_creatable_before_save!(ActiveModel);
