//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "cart"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub customer_id: Option<i64>,
    pub status: String,
    pub expires_at: Option<DateTime>,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    CustomerId,
    Status,
    ExpiresAt,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Tenant,
    Customer,
    CartItem,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::CustomerId => ColumnType::Integer.def().null(),
            Self::Status => ColumnType::String(StringLen::N(20u32)).def(),
            Self::ExpiresAt => ColumnType::DateTime.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
            Self::Customer => Entity::belongs_to(super::customer_entity::Entity)
                .from((Column::TenantId, Column::CustomerId))
                .to((
                    super::customer_entity::Column::TenantId,
                    super::customer_entity::Column::Id,
                ))
                .into(),
            Self::CartItem => Entity::has_many(super::cart_item_entity::Entity).into(),
        }
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl Related<super::customer_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::cart_item_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CartItem.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
