//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "catalog_attribute"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub name: String,
    pub display_type: String,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Name,
    DisplayType,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CatalogAttributeValue,
    ProductAttribute,
    Tenant,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::N(80u32)).def(),
            Self::DisplayType => ColumnType::String(StringLen::N(20u32)).def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CatalogAttributeValue => {
                Entity::has_many(super::catalog_attribute_value_entity::Entity).into()
            }
            Self::ProductAttribute => {
                Entity::has_many(super::product_attribute_entity::Entity).into()
            }
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
        }
    }
}

impl Related<super::catalog_attribute_value_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatalogAttributeValue.def()
    }
}

impl Related<super::product_attribute_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttribute.def()
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
