//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "category"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub name: String,
    pub slug: String,
    pub parent_id: Option<i64>,
    pub active: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Name,
    Slug,
    ParentId,
    Active,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    SelfRef,
    ProductCategory,
    Tenant,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::N(120u32)).def(),
            Self::Slug => ColumnType::String(StringLen::N(140u32)).def(),
            Self::ParentId => ColumnType::Integer.def().null(),
            Self::Active => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::SelfRef => Entity::belongs_to(Entity)
                .from((Column::TenantId, Column::ParentId))
                .to((Column::TenantId, Column::Id))
                .into(),
            Self::ProductCategory => Entity::has_many(super::product_category_entity::Entity).into(),
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
        }
    }
}

impl Related<super::product_category_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategory.def()
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);