//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use sea_orm::Set;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "coupon_redemption"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub coupon_id: i64,
    pub order_id: i64,
    pub customer_id: i64,
    pub created_at: DateTime,
    pub created_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    CouponId,
    OrderId,
    CustomerId,
    CreatedAt,
    CreatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Coupon,
    Orders,
    Customer,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::CouponId => ColumnType::Integer.def(),
            Self::OrderId => ColumnType::Integer.def(),
            Self::CustomerId => ColumnType::Integer.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Coupon => Entity::belongs_to(super::coupon_entity::Entity)
                .from((Column::TenantId, Column::CouponId))
                .to((
                    super::coupon_entity::Column::TenantId,
                    super::coupon_entity::Column::Id,
                ))
                .into(),
            Self::Orders => Entity::belongs_to(super::orders_entity::Entity)
                .from((Column::TenantId, Column::OrderId))
                .to((
                    super::orders_entity::Column::TenantId,
                    super::orders_entity::Column::Id,
                ))
                .into(),
            Self::Customer => Entity::belongs_to(super::customer_entity::Entity)
                .from(Column::CustomerId)
                .to(super::customer_entity::Column::Id)
                .into(),
        }
    }
}

impl Related<super::coupon_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coupon.def()
    }
}

impl Related<super::orders_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::customer_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl crate::audit_entity::CreatableActiveModel for ActiveModel {
    fn set_uuid(&mut self) {
        self.uuid = Set(uuid::Uuid::new_v4());
    }

    fn set_created_at(&mut self, value: DateTime) {
        self.created_at = Set(value);
    }

    fn set_created_by(&mut self, value: Option<String>) {
        self.created_by = Set(value);
    }
}

#[sea_orm::prelude::async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        Ok(crate::audit_entity::stamp_creation(self, insert).await)
    }
}
