//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "coupon"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub code: String,
    pub campaign_id: Option<i64>,
    pub coupon_type: String,
    pub value: i32,
    pub min_order_cents: Option<i32>,
    pub max_uses: Option<i32>,
    pub max_uses_per_customer: Option<i32>,
    pub starts_at: Option<DateTime>,
    pub expires_at: Option<DateTime>,
    pub active: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Code,
    CampaignId,
    #[sea_orm(column_name = "coupon_type")]
    CouponType,
    Value,
    MinOrderCents,
    MaxUses,
    MaxUsesPerCustomer,
    StartsAt,
    ExpiresAt,
    Active,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Tenant,
    Campaign,
    Orders,
    CouponRedemption,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::Code => ColumnType::String(StringLen::N(40u32)).def(),
            Self::CampaignId => ColumnType::Integer.def().null(),
            Self::CouponType => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Value => ColumnType::Integer.def(),
            Self::MinOrderCents => ColumnType::Integer.def().null(),
            Self::MaxUses => ColumnType::Integer.def().null(),
            Self::MaxUsesPerCustomer => ColumnType::Integer.def().null(),
            Self::StartsAt => ColumnType::DateTime.def().null(),
            Self::ExpiresAt => ColumnType::DateTime.def().null(),
            Self::Active => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
            Self::Campaign => Entity::belongs_to(super::campaign_entity::Entity)
                .from((Column::TenantId, Column::CampaignId))
                .to((
                    super::campaign_entity::Column::TenantId,
                    super::campaign_entity::Column::Id,
                ))
                .into(),
            Self::Orders => Entity::has_many(super::orders_entity::Entity).into(),
            Self::CouponRedemption => {
                Entity::has_many(super::coupon_redemption_entity::Entity).into()
            }
        }
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl Related<super::campaign_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Campaign.def()
    }
}

impl Related<super::orders_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::coupon_redemption_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponRedemption.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
