//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "customer"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub name: String,
    pub email: String,
    pub password_hash: String,
    pub cpf: Option<String>,
    pub phone: Option<String>,
    pub marketing_consent: bool,
    pub consent_at: Option<DateTime>,
    pub active: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Name,
    Email,
    PasswordHash,
    Cpf,
    Phone,
    MarketingConsent,
    ConsentAt,
    Active,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Tenant,
    CustomerAddress,
    Cart,
    Orders,
    CouponRedemption,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::N(150u32)).def(),
            Self::Email => ColumnType::String(StringLen::N(190u32)).def(),
            Self::PasswordHash => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Cpf => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Phone => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::MarketingConsent => ColumnType::Boolean.def(),
            Self::ConsentAt => ColumnType::DateTime.def().null(),
            Self::Active => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
            Self::CustomerAddress => {
                Entity::has_many(super::customer_address_entity::Entity).into()
            }
            Self::Cart => Entity::has_many(super::cart_entity::Entity).into(),
            Self::Orders => Entity::has_many(super::orders_entity::Entity).into(),
            Self::CouponRedemption => {
                Entity::has_many(super::coupon_redemption_entity::Entity).into()
            }
        }
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl Related<super::customer_address_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerAddress.def()
    }
}

impl Related<super::cart_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cart.def()
    }
}

impl Related<super::orders_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::coupon_redemption_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponRedemption.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
