//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "customer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub user_id: Option<i64>,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub cpf: Option<String>,
    pub phone: Option<String>,
    pub marketing_consent: bool,
    pub consent_at: Option<DateTime>,
    pub active: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::customer_address_entity::Entity")]
    CustomerAddress,
}

impl Related<super::customer_address_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerAddress.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
