//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "order_item"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub order_id: i64,
    pub sku_id: i64,
    pub sku_code: String,
    pub product_name: String,
    pub attributes_desc: Option<String>,
    pub quantity: i32,
    pub unit_price_cents: i32,
    pub discount_cents: i32,
    pub ncm: String,
    pub cfop: String,
    pub csosn: String,
    pub icms_rate_bp: i32,
    pub tax_cents: i32,
    pub total_cents: i32,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    OrderId,
    SkuId,
    SkuCode,
    ProductName,
    AttributesDesc,
    Quantity,
    UnitPriceCents,
    DiscountCents,
    Ncm,
    Cfop,
    Csosn,
    IcmsRateBp,
    TaxCents,
    TotalCents,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Orders,
    Sku,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::OrderId => ColumnType::Integer.def(),
            Self::SkuId => ColumnType::Integer.def(),
            Self::SkuCode => ColumnType::String(StringLen::N(64u32)).def(),
            Self::ProductName => ColumnType::String(StringLen::N(200u32)).def(),
            Self::AttributesDesc => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Quantity => ColumnType::Integer.def(),
            Self::UnitPriceCents => ColumnType::Integer.def(),
            Self::DiscountCents => ColumnType::Integer.def(),
            Self::Ncm => ColumnType::String(StringLen::N(8u32)).def(),
            Self::Cfop => ColumnType::String(StringLen::N(4u32)).def(),
            Self::Csosn => ColumnType::String(StringLen::N(4u32)).def(),
            Self::IcmsRateBp => ColumnType::Integer.def(),
            Self::TaxCents => ColumnType::Integer.def(),
            Self::TotalCents => ColumnType::Integer.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Orders => Entity::belongs_to(super::orders_entity::Entity)
                .from((Column::TenantId, Column::OrderId))
                .to((
                    super::orders_entity::Column::TenantId,
                    super::orders_entity::Column::Id,
                ))
                .into(),
            Self::Sku => Entity::belongs_to(super::sku_entity::Entity)
                .from((Column::TenantId, Column::SkuId))
                .to((
                    super::sku_entity::Column::TenantId,
                    super::sku_entity::Column::Id,
                ))
                .into(),
        }
    }
}

impl Related<super::orders_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::sku_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sku.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
