//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "orders"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub number: String,
    pub customer_id: i64,
    pub status: String,
    pub payment_status: String,
    pub subtotal_cents: i32,
    pub discount_cents: i32,
    pub shipping_cents: i32,
    pub tax_total_cents: i32,
    pub total_cents: i32,
    pub coupon_id: Option<i64>,
    pub coupon_code: Option<String>,
    pub ship_recipient: String,
    pub ship_cep: String,
    pub ship_logradouro: String,
    pub ship_numero: String,
    pub ship_complemento: Option<String>,
    pub ship_bairro: String,
    pub ship_cidade: String,
    pub ship_uf: String,
    pub placed_at: DateTime,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Number,
    CustomerId,
    Status,
    PaymentStatus,
    SubtotalCents,
    DiscountCents,
    ShippingCents,
    TaxTotalCents,
    TotalCents,
    CouponId,
    CouponCode,
    ShipRecipient,
    ShipCep,
    ShipLogradouro,
    ShipNumero,
    ShipComplemento,
    ShipBairro,
    ShipCidade,
    ShipUf,
    PlacedAt,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Tenant,
    Customer,
    Coupon,
    OrderItem,
    OrderStatusHistory,
    CouponRedemption,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::Number => ColumnType::String(StringLen::N(20u32)).def(),
            Self::CustomerId => ColumnType::Integer.def(),
            Self::Status => ColumnType::String(StringLen::N(30u32)).def(),
            Self::PaymentStatus => ColumnType::String(StringLen::N(30u32)).def(),
            Self::SubtotalCents => ColumnType::Integer.def(),
            Self::DiscountCents => ColumnType::Integer.def(),
            Self::ShippingCents => ColumnType::Integer.def(),
            Self::TaxTotalCents => ColumnType::Integer.def(),
            Self::TotalCents => ColumnType::Integer.def(),
            Self::CouponId => ColumnType::Integer.def().null(),
            Self::CouponCode => ColumnType::String(StringLen::N(40u32)).def().null(),
            Self::ShipRecipient => ColumnType::String(StringLen::N(150u32)).def(),
            Self::ShipCep => ColumnType::String(StringLen::N(8u32)).def(),
            Self::ShipLogradouro => ColumnType::String(StringLen::N(200u32)).def(),
            Self::ShipNumero => ColumnType::String(StringLen::N(20u32)).def(),
            Self::ShipComplemento => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::ShipBairro => ColumnType::String(StringLen::N(100u32)).def(),
            Self::ShipCidade => ColumnType::String(StringLen::N(100u32)).def(),
            Self::ShipUf => ColumnType::String(StringLen::N(2u32)).def(),
            Self::PlacedAt => ColumnType::DateTime.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
            Self::Customer => Entity::belongs_to(super::customer_entity::Entity)
                .from((Column::TenantId, Column::CustomerId))
                .to((
                    super::customer_entity::Column::TenantId,
                    super::customer_entity::Column::Id,
                ))
                .into(),
            Self::Coupon => Entity::belongs_to(super::coupon_entity::Entity)
                .from((Column::TenantId, Column::CouponId))
                .to((
                    super::coupon_entity::Column::TenantId,
                    super::coupon_entity::Column::Id,
                ))
                .into(),
            Self::OrderItem => Entity::has_many(super::order_item_entity::Entity).into(),
            Self::OrderStatusHistory => {
                Entity::has_many(super::order_status_history_entity::Entity).into()
            }
            Self::CouponRedemption => {
                Entity::has_many(super::coupon_redemption_entity::Entity).into()
            }
        }
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl Related<super::customer_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::coupon_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coupon.def()
    }
}

impl Related<super::order_item_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItem.def()
    }
}

impl Related<super::order_status_history_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderStatusHistory.def()
    }
}

impl Related<super::coupon_redemption_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponRedemption.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
