//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "person_address")]
pub struct Model {
    #[sea_orm(primary_key, unique_key = "uq_persons_address_tenant_id_id")]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    #[sea_orm(unique_key = "uq_persons_address_tenant_id_id")]
    pub tenant_id: Option<i64>,
    pub person_id: i64,
    pub address_line1: Option<String>,
    pub address_line2: Option<String>,
    pub locality: Option<String>,
    pub administrative_area: Option<String>,
    pub postal_code: Option<String>,
    pub country_code: Option<String>,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::person_entity::Entity",
        from = "(Column::PersonId, Column::TenantId)",
        to = "(super::person_entity::Column::Id, super::person_entity::Column::TenantId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Person,
}

impl Related<super::person_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Person.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
