//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "person")]
pub struct Model {
    #[sea_orm(primary_key, unique_key = "uq_persosn_tenant_id_id")]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    #[sea_orm(unique_key = "uq_persosn_tenant_id_id")]
    pub tenant_id: Option<i64>,
    pub user_id: i64,
    pub first_name: String,
    pub surname: Option<String>,
    pub date_of_birth: Option<Date>,
    pub gender: Option<String>,
    pub avatar: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::person_address_entity::Entity")]
    PersonAddress,
    #[sea_orm(
        belongs_to = "super::user_entity::Entity",
        from = "Column::UserId",
        to = "super::user_entity::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    User,
}

impl Related<super::person_address_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonAddress.def()
    }
}

impl Related<super::user_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
