//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "product_category"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub product_id: i64,
    pub category_id: i64,
    pub is_primary: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    ProductId,
    CategoryId,
    IsPrimary,
    CreatedAt,
    CreatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Category,
    Product,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::ProductId => ColumnType::Integer.def(),
            Self::CategoryId => ColumnType::Integer.def(),
            Self::IsPrimary => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Category => Entity::belongs_to(super::category_entity::Entity)
                .from((Column::TenantId, Column::CategoryId))
                .to((
                    super::category_entity::Column::TenantId,
                    super::category_entity::Column::Id,
                ))
                .into(),
            Self::Product => Entity::belongs_to(super::product_entity::Entity)
                .from((Column::TenantId, Column::ProductId))
                .to((
                    super::product_entity::Column::TenantId,
                    super::product_entity::Column::Id,
                ))
                .into(),
        }
    }
}

impl Related<super::category_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::product_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

crate::impl_tenant_creatable_before_save!(ActiveModel);
