//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "product_image"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Vec<u8>,
    pub tenant_id: Option<i64>,
    pub product_id: i64,
    pub sku_id: Option<i64>,
    pub alt_text: Option<String>,
    pub sort_order: i32,
    pub is_primary: bool,
    pub storage_provider: String,
    pub bucket: String,
    pub object_key: String,
    pub storage_identity_hash: Vec<u8>,
    pub object_version: Option<String>,
    pub etag: Option<String>,
    pub checksum_sha256: Option<Vec<u8>>,
    pub original_filename: String,
    pub mime_type: String,
    pub size_bytes: i64,
    pub width_px: Option<i32>,
    pub height_px: Option<i32>,
    pub storage_status: String,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub deleted_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    ProductId,
    SkuId,
    AltText,
    SortOrder,
    IsPrimary,
    StorageProvider,
    Bucket,
    ObjectKey,
    StorageIdentityHash,
    ObjectVersion,
    Etag,
    ChecksumSha256,
    OriginalFilename,
    MimeType,
    SizeBytes,
    WidthPx,
    HeightPx,
    StorageStatus,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
    DeletedAt,
    DeletedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Product,
    Sku,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::VarBinary(StringLen::None).def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::ProductId => ColumnType::Integer.def(),
            Self::SkuId => ColumnType::Integer.def().null(),
            Self::AltText => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::SortOrder => ColumnType::Integer.def(),
            Self::IsPrimary => ColumnType::Boolean.def(),
            Self::StorageProvider => ColumnType::String(StringLen::N(32u32)).def(),
            Self::Bucket => ColumnType::String(StringLen::N(255u32)).def(),
            Self::ObjectKey => ColumnType::String(StringLen::N(1024u32)).def(),
            Self::StorageIdentityHash => ColumnType::VarBinary(StringLen::None).def().unique(),
            Self::ObjectVersion => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Etag => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::ChecksumSha256 => ColumnType::VarBinary(StringLen::None).def().null(),
            Self::OriginalFilename => ColumnType::String(StringLen::N(255u32)).def(),
            Self::MimeType => ColumnType::String(StringLen::N(127u32)).def(),
            Self::SizeBytes => ColumnType::BigInteger.def(),
            Self::WidthPx => ColumnType::Integer.def().null(),
            Self::HeightPx => ColumnType::Integer.def().null(),
            Self::StorageStatus => ColumnType::String(StringLen::N(20u32)).def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
            Self::DeletedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Product => Entity::belongs_to(super::product_entity::Entity)
                .from((Column::TenantId, Column::ProductId))
                .to((super::product_entity::Column::TenantId, super::product_entity::Column::Id))
                .into(),
            Self::Sku => Entity::belongs_to(super::sku_entity::Entity)
                .from((Column::TenantId, Column::SkuId, Column::ProductId))
                .to((
                    super::sku_entity::Column::TenantId,
                    super::sku_entity::Column::Id,
                    super::sku_entity::Column::ProductId,
                ))
                .into(),
        }
    }
}

impl Related<super::product_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl Related<super::sku_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sku.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel, binary_uuid);
