//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "product"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub name: String,
    pub slug: String,
    pub description: Option<String>,
    pub brand: Option<String>,
    pub active: bool,
    pub ncm: String,
    pub cest: Option<String>,
    pub origem_mercadoria: i16,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Name,
    Slug,
    Description,
    Brand,
    Active,
    Ncm,
    Cest,
    OrigemMercadoria,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ProductAttribute,
    ProductCategory,
    ProductImage,
    Sku,
    Tenant,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::N(200u32)).def(),
            Self::Slug => ColumnType::String(StringLen::N(220u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::Brand => ColumnType::String(StringLen::N(120u32)).def().null(),
            Self::Active => ColumnType::Boolean.def(),
            Self::Ncm => ColumnType::String(StringLen::N(8u32)).def(),
            Self::Cest => ColumnType::String(StringLen::N(7u32)).def().null(),
            Self::OrigemMercadoria => ColumnType::SmallInteger.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ProductAttribute => Entity::has_many(super::product_attribute_entity::Entity).into(),
            Self::ProductCategory => Entity::has_many(super::product_category_entity::Entity).into(),
            Self::ProductImage => Entity::has_many(super::product_image_entity::Entity).into(),
            Self::Sku => Entity::has_many(super::sku_entity::Entity).into(),
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
        }
    }
}

impl Related<super::product_attribute_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttribute.def()
    }
}

impl Related<super::product_category_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductCategory.def()
    }
}

impl Related<super::product_image_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductImage.def()
    }
}

impl Related<super::sku_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sku.def()
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);