//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sku_attribute_value")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "uq_sku_attribute_value_sku_attribute_value")]
    pub sku_id: i32,
    #[sea_orm(unique_key = "uq_sku_attribute_value_sku_attribute_value")]
    pub attribute_value_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_attribute_value::Entity",
        from = "Column::AttributeValueId",
        to = "super::product_attribute_value::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ProductAttributeValue,
    #[sea_orm(
        belongs_to = "super::sku::Entity",
        from = "Column::SkuId",
        to = "super::sku::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Sku,
}

impl Related<super::product_attribute_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttributeValue.def()
    }
}

impl Related<super::sku::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sku.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
