//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "sku"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub product_id: i64,
    pub code: String,
    pub variant_key: String,
    pub price_cents: i32,
    pub compare_at_price_cents: Option<i32>,
    pub weight_g: Option<i32>,
    pub width_mm: Option<i32>,
    pub height_mm: Option<i32>,
    pub length_mm: Option<i32>,
    pub active: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    ProductId,
    Code,
    VariantKey,
    PriceCents,
    CompareAtPriceCents,
    WeightG,
    WidthMm,
    HeightMm,
    LengthMm,
    Active,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Product,
    ProductImage,
    SkuAttributeValue,
    SkuStock,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::Integer.def(),
            Self::ProductId => ColumnType::Integer.def(),
            Self::Code => ColumnType::String(StringLen::N(64u32)).def(),
            Self::VariantKey => ColumnType::String(StringLen::N(64u32)).def(),
            Self::PriceCents => ColumnType::Integer.def(),
            Self::CompareAtPriceCents => ColumnType::Integer.def().null(),
            Self::WeightG => ColumnType::Integer.def().null(),
            Self::WidthMm => ColumnType::Integer.def().null(),
            Self::HeightMm => ColumnType::Integer.def().null(),
            Self::LengthMm => ColumnType::Integer.def().null(),
            Self::Active => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Product => Entity::belongs_to(super::product_entity::Entity)
                .from((Column::TenantId, Column::ProductId))
                .to((super::product_entity::Column::TenantId, super::product_entity::Column::Id))
                .into(),
            Self::ProductImage => Entity::has_many(super::product_image_entity::Entity).into(),
            Self::SkuAttributeValue => Entity::has_many(super::sku_attribute_value_entity::Entity).into(),
            Self::SkuStock => Entity::has_many(super::sku_stock_entity::Entity).into(),
        }
    }
}

impl Related<super::product_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl Related<super::product_image_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductImage.def()
    }
}

impl Related<super::sku_attribute_value_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SkuAttributeValue.def()
    }
}

impl Related<super::sku_stock_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SkuStock.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);