//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "tenant"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub business_name: String,
    pub company_name: Option<String>,
    pub tax_id: String,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub web_site: Option<String>,
    pub address_line1: Option<String>,
    pub address_line2: Option<String>,
    pub locality: Option<String>,
    pub administrative_area: Option<String>,
    pub postal_code: Option<String>,
    pub country_code: Option<String>,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    BusinessName,
    CompanyName,
    TaxId,
    Email,
    Phone,
    WebSite,
    AddressLine1,
    AddressLine2,
    Locality,
    AdministrativeArea,
    PostalCode,
    CountryCode,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CatalogAttribute,
    Category,
    Product,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::BusinessName => ColumnType::String(StringLen::N(500u32)).def(),
            Self::CompanyName => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::TaxId => ColumnType::String(StringLen::N(100u32)).def(),
            Self::Email => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::Phone => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::WebSite => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::AddressLine1 => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::AddressLine2 => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::Locality => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::AdministrativeArea => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::PostalCode => ColumnType::String(StringLen::N(32u32)).def().null(),
            Self::CountryCode => ColumnType::String(StringLen::N(2u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def().null(),
            Self::CreatedBy => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def().null(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(50u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CatalogAttribute => {
                Entity::has_many(super::catalog_attribute_entity::Entity).into()
            }
            Self::Category => Entity::has_many(super::category_entity::Entity).into(),
            Self::Product => Entity::has_many(super::product_entity::Entity).into(),
        }
    }
}

impl Related<super::catalog_attribute_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CatalogAttribute.def()
    }
}

impl Related<super::category_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::product_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

crate::impl_auditable_before_save!(ActiveModel);
