//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "warehouse"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uuid: Uuid,
    pub tenant_id: Option<i64>,
    pub name: String,
    pub origin_cep: String,
    pub street: Option<String>,
    pub number: Option<String>,
    pub complement: Option<String>,
    pub district: Option<String>,
    pub city: String,
    pub uf: String,
    pub is_default: bool,
    pub active: bool,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: DateTime,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uuid,
    TenantId,
    Name,
    OriginCep,
    Street,
    Number,
    Complement,
    District,
    City,
    Uf,
    IsDefault,
    Active,
    CreatedAt,
    CreatedBy,
    UpdatedAt,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Tenant,
    SkuStock,
    ShippingRate,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Uuid => ColumnType::Uuid.def().unique(),
            Self::TenantId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::N(100u32)).def(),
            Self::OriginCep => ColumnType::String(StringLen::N(8u32)).def(),
            Self::Street => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Number => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Complement => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::District => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::City => ColumnType::String(StringLen::N(100u32)).def(),
            Self::Uf => ColumnType::String(StringLen::N(2u32)).def(),
            Self::IsDefault => ColumnType::Boolean.def(),
            Self::Active => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::CreatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UpdatedBy => ColumnType::String(StringLen::N(255u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Tenant => Entity::belongs_to(super::tenant_entity::Entity)
                .from(Column::TenantId)
                .to(super::tenant_entity::Column::Id)
                .into(),
            Self::SkuStock => Entity::has_many(super::sku_stock_entity::Entity).into(),
            Self::ShippingRate => Entity::has_many(super::shipping_rate_entity::Entity).into(),
        }
    }
}

impl Related<super::tenant_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenant.def()
    }
}

impl Related<super::sku_stock_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SkuStock.def()
    }
}

impl Related<super::shipping_rate_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingRate.def()
    }
}

crate::impl_tenant_auditable_before_save!(ActiveModel);
