import fs from "node:fs";
import path from "node:path";

const outDir = path.resolve("data/wines");
fs.mkdirSync(outDir, { recursive: true });

const realWines = [
  // --- BRASIL (7) ---
  {
    key: "wine-br-001",
    name: "Miolo Lote 43 Tinto",
    slug: "miolo-lote-43-tinto",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Miolo Wine Group",
    origem: 0,
    country: "Brasil",
    region: "Vale dos Vinhedos",
    grape: "Cabernet Sauvignon, Merlot",
    vintage: "2020",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Ícone da vitivinicultura brasileira elaborado apenas em safras excepcionais no Vale dos Vinhedos, amadurecido 12 meses em barricas de carvalho francês.",
    priceCents: 25900,
    compareAtPriceCents: 28900,
    stock: 48,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-br-002",
    name: "Casa Valduga 130 Brut",
    slug: "casa-valduga-130-brut",
    categoryKey: "espumantes-champagnes",
    categoryName: "Espumantes & Champagnes",
    brand: "Casa Valduga",
    origem: 0,
    country: "Brasil",
    region: "Vale dos Vinhedos",
    grape: "Chardonnay, Pinot Noir",
    vintage: "NV",
    alcohol: "12.0%",
    color: "Espumante",
    description: "Espumante ícone brasileiro elaborado pelo método tradicional (champenoise) com 36 meses de evolução em caves subterrâneas.",
    priceCents: 16900,
    compareAtPriceCents: 18900,
    stock: 60,
    volume: "750ml",
    weightG: 1450,
    widthMm: 85,
    heightMm: 320,
    lengthMm: 85,
  },
  {
    key: "wine-br-003",
    name: "Guaspari Vista do Chá Syrah",
    slug: "guaspari-vista-do-cha-syrah",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Vinícola Guaspari",
    origem: 0,
    country: "Brasil",
    region: "Espírito Santo do Pinhal",
    grape: "Syrah",
    vintage: "2021",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Vinho de colheita de inverno da Serra da Mantiqueira, premiado internacionalmente por sua complexidade aromática e elegância.",
    priceCents: 34000,
    compareAtPriceCents: 38000,
    stock: 36,
    volume: "750ml",
    weightG: 1380,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-br-004",
    name: "Salton Talento Tinto",
    slug: "salton-talento-tinto",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Vinícola Salton",
    origem: 0,
    country: "Brasil",
    region: "Campanha Gaúcha",
    grape: "Cabernet Sauvignon, Merlot, Tannat",
    vintage: "2020",
    alcohol: "13.5%",
    color: "Tinto",
    description: "Corte clássico brasileiro com notas de frutas vermelhas maduras, baunilha e taninos estruturados, com estágio de 12 meses em barricas.",
    priceCents: 14900,
    compareAtPriceCents: 17000,
    stock: 50,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-br-005",
    name: "Pizzato DNA Merlot",
    slug: "pizzato-dna-merlot",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Pizzato Vinhas e Vinhos",
    origem: 0,
    country: "Brasil",
    region: "Vale dos Vinhedos",
    grape: "Merlot",
    vintage: "2020",
    alcohol: "14.0%",
    color: "Tinto",
    description: "A máxima expressão da uva Merlot no Vale dos Vinhedos, vinificado com vinhas velhas e maturação criteriosa em carvalho francês.",
    priceCents: 22000,
    compareAtPriceCents: 25000,
    stock: 40,
    volume: "750ml",
    weightG: 1360,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-br-006",
    name: "Cave Geisse Terroir Brut Nature",
    slug: "cave-geisse-terroir-brut-nature",
    categoryKey: "espumantes-champagnes",
    categoryName: "Espumantes & Champagnes",
    brand: "Família Geisse",
    origem: 0,
    country: "Brasil",
    region: "Pinto Bandeira",
    grape: "Chardonnay, Pinot Noir",
    vintage: "2019",
    alcohol: "12.5%",
    color: "Espumante",
    description: "Elaborado na D.O. Pinto Bandeira pelo renomado enólogo Mário Geisse com 42 meses de autólise sobre as leveduras.",
    priceCents: 23900,
    compareAtPriceCents: 26900,
    stock: 42,
    volume: "750ml",
    weightG: 1480,
    widthMm: 85,
    heightMm: 320,
    lengthMm: 85,
  },
  {
    key: "wine-br-007",
    name: "Luiz Argenta Cave Corte Tinto",
    slug: "luiz-argenta-cave-corte-tinto",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Luiz Argenta",
    origem: 0,
    country: "Brasil",
    region: "Flores da Cunha",
    grape: "Merlot, Cabernet Franc",
    vintage: "2018",
    alcohol: "13.8%",
    color: "Tinto",
    description: "Envelhecido 24 meses em carvalho francês, destaca-se pela garrafa italiana exclusiva e perfil aveludado com notas de especiarias e trufas.",
    priceCents: 28500,
    compareAtPriceCents: 32000,
    stock: 30,
    volume: "750ml",
    weightG: 1420,
    widthMm: 82,
    heightMm: 325,
    lengthMm: 82,
  },

  // --- ARGENTINA (8) ---
  {
    key: "wine-ar-008",
    name: "Catena Zapata Malbec Argentino",
    slug: "catena-zapata-malbec-argentino",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Bodega Catena Zapata",
    origem: 1,
    country: "Argentina",
    region: "Mendoza",
    grape: "Malbec",
    vintage: "2021",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Obra-prima de Nicolás e Laura Catena unindo vinhas históricas de Nicasia e Adrianna em vinhedos de extrema altitude.",
    priceCents: 98000,
    compareAtPriceCents: 115000,
    stock: 24,
    volume: "750ml",
    weightG: 1400,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-ar-009",
    name: "Nicolás Catena Zapata",
    slug: "nicolas-catena-zapata",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Bodega Catena Zapata",
    origem: 1,
    country: "Argentina",
    region: "Mendoza",
    grape: "Cabernet Sauvignon, Malbec",
    vintage: "2019",
    alcohol: "14.0%",
    color: "Tinto",
    description: "O pioneiro Super-Argentino que desafiou os grandes vinhos do mundo em degustações às cegas históricas.",
    priceCents: 135000,
    compareAtPriceCents: 155000,
    stock: 18,
    volume: "750ml",
    weightG: 1450,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-ar-010",
    name: "Rutini Cabernet-Malbec",
    slug: "rutini-cabernet-malbec",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Rutini Wines",
    origem: 1,
    country: "Argentina",
    region: "Mendoza",
    grape: "Cabernet Sauvignon, Malbec",
    vintage: "2021",
    alcohol: "14.0%",
    color: "Tinto",
    description: "O mais consagrado blend da enologia argentina assinado pelo enólogo Mariano Di Paola, com 12 meses em barricas francesas e americanas.",
    priceCents: 28900,
    compareAtPriceCents: 32900,
    stock: 60,
    volume: "750ml",
    weightG: 1360,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-ar-011",
    name: "Alma Negra Misterio",
    slug: "alma-negra-misterio",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Ernesto Catena Vineyards",
    origem: 1,
    country: "Argentina",
    region: "Mendoza",
    grape: "Bonarda, Malbec",
    vintage: "2020",
    alcohol: "13.5%",
    color: "Tinto",
    description: "Corte secreto emblemático criado por Ernesto Catena que combina exuberância frutada e textura sedosa irresistível.",
    priceCents: 23900,
    compareAtPriceCents: 27500,
    stock: 54,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-ar-012",
    name: "El Enemigo Cabernet Franc",
    slug: "el-enemigo-cabernet-franc",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Bodega Aleanna",
    origem: 1,
    country: "Argentina",
    region: "Gualtallary",
    grape: "Cabernet Franc",
    vintage: "2020",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Criação magistral de Alejandro Vigil em Gualtallary, fermentado em foudres centenários com grande mineralidade e frescor.",
    priceCents: 29900,
    compareAtPriceCents: 34000,
    stock: 48,
    volume: "750ml",
    weightG: 1370,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-ar-013",
    name: "Luigi Bosca De Sangre Malbec",
    slug: "luigi-bosca-de-sangre-malbec",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Luigi Bosca",
    origem: 1,
    country: "Argentina",
    region: "Valle de Uco",
    grape: "Malbec",
    vintage: "2020",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Expressão profunda da uva Malbec cultivada em solos calcários de altitude no Valle de Uco pela secular família Arizu.",
    priceCents: 31000,
    compareAtPriceCents: 35500,
    stock: 36,
    volume: "750ml",
    weightG: 1380,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-ar-014",
    name: "Terrazas de los Andes Reserva Malbec",
    slug: "terrazas-de-los-andes-reserva-malbec",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Terrazas de los Andes",
    origem: 1,
    country: "Argentina",
    region: "Mendoza",
    grape: "Malbec",
    vintage: "2022",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Vinho frutado e envolvente de vinhedos plantados em terraços nas encostas da Cordilheira dos Andes.",
    priceCents: 13900,
    compareAtPriceCents: 16500,
    stock: 72,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-ar-015",
    name: "Salentein Primus Malbec",
    slug: "salentein-primus-malbec",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Bodegas Salentein",
    origem: 1,
    country: "Argentina",
    region: "Valle de Uco",
    grape: "Malbec",
    vintage: "2019",
    alcohol: "15.0%",
    color: "Tinto",
    description: "O topo de gama da Salentein, produzido a partir de parcelas selecionadas a mais de 1.150 metros de altitude com 18 meses em carvalho.",
    priceCents: 56000,
    compareAtPriceCents: 62000,
    stock: 24,
    volume: "750ml",
    weightG: 1420,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },

  // --- CHILE (8) ---
  {
    key: "wine-cl-016",
    name: "Don Melchor Cabernet Sauvignon",
    slug: "don-melchor-cabernet-sauvignon",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Viña Concha y Toro",
    origem: 1,
    country: "Chile",
    region: "Puente Alto",
    grape: "Cabernet Sauvignon",
    vintage: "2020",
    alcohol: "14.5%",
    color: "Tinto",
    description: "O primeiro vinho ícone chileno, elaborado no célebre terroir aluvial de Puente Alto sob a consultoria de Jacques Boissenot.",
    priceCents: 119000,
    compareAtPriceCents: 135000,
    stock: 24,
    volume: "750ml",
    weightG: 1450,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-cl-017",
    name: "Montes Alpha Cabernet Sauvignon",
    slug: "montes-alpha-cabernet-sauvignon",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Viña Montes",
    origem: 1,
    country: "Chile",
    region: "Valle de Colchagua",
    grape: "Cabernet Sauvignon",
    vintage: "2021",
    alcohol: "14.5%",
    color: "Tinto",
    description: "O vinho que iniciou a era dos vinhos finos chilenos de exportação pelas mãos do visionário Aurelio Montes.",
    priceCents: 18900,
    compareAtPriceCents: 22000,
    stock: 80,
    volume: "750ml",
    weightG: 1360,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-cl-018",
    name: "Almaviva",
    slug: "almaviva",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Viña Almaviva",
    origem: 1,
    country: "Chile",
    region: "Puente Alto",
    grape: "Cabernet Sauvignon, Carmenère, Cabernet Franc",
    vintage: "2019",
    alcohol: "15.0%",
    color: "Tinto",
    description: "Parceria lendária entre a Baronesa Philippine de Rothschild (Château Mouton Rothschild) e a Concha y Toro.",
    priceCents: 185000,
    compareAtPriceCents: 210000,
    stock: 16,
    volume: "750ml",
    weightG: 1500,
    widthMm: 85,
    heightMm: 325,
    lengthMm: 85,
  },
  {
    key: "wine-cl-019",
    name: "Seña",
    slug: "sena",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Viña Seña",
    origem: 1,
    country: "Chile",
    region: "Valle de Aconcagua",
    grape: "Cabernet Sauvignon, Malbec, Carmenère",
    vintage: "2020",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Fruto da aliança entre Eduardo Chadwick e Robert Mondavi, cultivado sob rigorosos preceitos biodinâmicos no Aconcagua.",
    priceCents: 169000,
    compareAtPriceCents: 195000,
    stock: 18,
    volume: "750ml",
    weightG: 1480,
    widthMm: 84,
    heightMm: 320,
    lengthMm: 84,
  },
  {
    key: "wine-cl-020",
    name: "Clos Apalta",
    slug: "clos-apalta",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Clos Apalta",
    origem: 1,
    country: "Chile",
    region: "Valle de Apalta",
    grape: "Carmenère, Cabernet Sauvignon, Merlot",
    vintage: "2018",
    alcohol: "15.0%",
    color: "Tinto",
    description: "Colecionador de pontuações perfeitas (100 pontos), vinificado por gravidade com leveduras nativas e vinhas pré-filoxéricas.",
    priceCents: 149000,
    compareAtPriceCents: 170000,
    stock: 20,
    volume: "750ml",
    weightG: 1480,
    widthMm: 84,
    heightMm: 320,
    lengthMm: 84,
  },
  {
    key: "wine-cl-021",
    name: "Vik Milla Cala",
    slug: "vik-milla-cala",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Viña VIK",
    origem: 1,
    country: "Chile",
    region: "Valle de Cachapoal",
    grape: "Cabernet Sauvignon, Carmenère, Syrah",
    vintage: "2019",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Mistura holística que homenageia a união entre a natureza do vale de Millahue e a paixão enológica dos proprietários Alex e Carrie Vik.",
    priceCents: 42000,
    compareAtPriceCents: 48000,
    stock: 36,
    volume: "750ml",
    weightG: 1400,
    widthMm: 82,
    heightMm: 318,
    lengthMm: 82,
  },
  {
    key: "wine-cl-022",
    name: "Marques de Casa Concha Cabernet Sauvignon",
    slug: "marques-de-casa-concha-cabernet-sauvignon",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Concha y Toro",
    origem: 1,
    country: "Chile",
    region: "Valle del Maipo",
    grape: "Cabernet Sauvignon",
    vintage: "2021",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Referência inquestionável de qualidade do Valle del Maipo, com concentração clássica de cassis e cedro.",
    priceCents: 14900,
    compareAtPriceCents: 17900,
    stock: 90,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-cl-023",
    name: "Errázuriz Don Maximiano Founder's Reserve",
    slug: "errazuriz-don-maximiano-founders-reserve",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Viña Errázuriz",
    origem: 1,
    country: "Chile",
    region: "Valle de Aconcagua",
    grape: "Cabernet Sauvignon",
    vintage: "2018",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Vinho de homenagem ao fundador Don Maximiano Errázuriz, símbolo da nobreza e pureza do terroir do Vale de Aconcágua.",
    priceCents: 89000,
    compareAtPriceCents: 105000,
    stock: 24,
    volume: "750ml",
    weightG: 1440,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },

  // --- FRANÇA (9) ---
  {
    key: "wine-fr-024",
    name: "Château Margaux Premier Grand Cru Classé",
    slug: "chateau-margaux-premier-grand-cru-classe",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Château Margaux",
    origem: 1,
    country: "França",
    region: "Bordeaux - Margaux",
    grape: "Cabernet Sauvignon, Merlot",
    vintage: "2017",
    alcohol: "13.5%",
    color: "Tinto",
    description: "Um dos cinco lendários Premiers Grands Crus Classés de Bordeaux de 1855, famoso pela finura aromática floral e longevidade transcendental.",
    priceCents: 790000,
    compareAtPriceCents: 880000,
    stock: 6,
    volume: "750ml",
    weightG: 1450,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-fr-025",
    name: "Dom Pérignon Vintage Champagne",
    slug: "dom-perignon-vintage-champagne",
    categoryKey: "espumantes-champagnes",
    categoryName: "Espumantes & Champagnes",
    brand: "Dom Pérignon",
    origem: 1,
    country: "França",
    region: "Champagne",
    grape: "Chardonnay, Pinot Noir",
    vintage: "2013",
    alcohol: "12.5%",
    color: "Espumante",
    description: "O ápice do champagne vintage, produzido unicamente em anos de safra perfeita com maturação prolongada em adegas históricas.",
    priceCents: 249000,
    compareAtPriceCents: 280000,
    stock: 18,
    volume: "750ml",
    weightG: 1600,
    widthMm: 90,
    heightMm: 325,
    lengthMm: 90,
  },
  {
    key: "wine-fr-026",
    name: "Veuve Clicquot Brut Yellow Label",
    slug: "veuve-clicquot-brut-yellow-label",
    categoryKey: "espumantes-champagnes",
    categoryName: "Espumantes & Champagnes",
    brand: "Veuve Clicquot",
    origem: 1,
    country: "França",
    region: "Champagne",
    grape: "Pinot Noir, Chardonnay, Pinot Meunier",
    vintage: "NV",
    alcohol: "12.0%",
    color: "Espumante",
    description: "O rótulo amarelo inconfundível que equilibra a potência do Pinot Noir com a vivacidade cítrica e o toque tostado do brioche.",
    priceCents: 54900,
    compareAtPriceCents: 62000,
    stock: 48,
    volume: "750ml",
    weightG: 1550,
    widthMm: 88,
    heightMm: 322,
    lengthMm: 88,
  },
  {
    key: "wine-fr-027",
    name: "Louis Jadot Chablis Premier Cru Fourchaume",
    slug: "louis-jadot-chablis-premier-cru-fourchaume",
    categoryKey: "vinhos-brancos",
    categoryName: "Vinhos Brancos",
    brand: "Maison Louis Jadot",
    origem: 1,
    country: "França",
    region: "Bourgogne - Chablis",
    grape: "Chardonnay",
    vintage: "2022",
    alcohol: "13.0%",
    color: "Branco",
    description: "Puro Chardonnay de solos calcários Kimmeridgianos que exibem mineralidade cortante de pedra de isqueiro e grande amplitude.",
    priceCents: 69000,
    compareAtPriceCents: 78000,
    stock: 30,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 310,
    lengthMm: 80,
  },
  {
    key: "wine-fr-028",
    name: "Château d'Yquem Premier Cru Supérieur Sauternes",
    slug: "chateau-dyquem-premier-cru-superieur-sauternes",
    categoryKey: "vinhos-sobremesa-fortificados",
    categoryName: "Vinhos de Sobremesa & Fortificados",
    brand: "Château d'Yquem",
    origem: 1,
    country: "França",
    region: "Bordeaux - Sauternes",
    grape: "Sémillon, Sauvignon Blanc",
    vintage: "2018",
    alcohol: "14.0%",
    color: "Sobremesa",
    description: "O mais supremo vinho doce botritizado do mundo, com complexidade infinita de damasco, mel de acácia, gengibre e açafrão.",
    priceCents: 420000,
    compareAtPriceCents: 480000,
    stock: 12,
    volume: "375ml",
    weightG: 750,
    widthMm: 62,
    heightMm: 245,
    lengthMm: 62,
  },
  {
    key: "wine-fr-029",
    name: "Château de Beaucastel Châteauneuf-du-Pape",
    slug: "chateau-de-beaucastel-chateauneuf-du-pape",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Famille Perrin",
    origem: 1,
    country: "França",
    region: "Vallée du Rhône",
    grape: "Mourvèdre, Grenache, Syrah",
    vintage: "2019",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Monumento do Vale do Ródano elaborado a partir das 13 castas históricas da denominação sobre o solo de galets roulés.",
    priceCents: 115000,
    compareAtPriceCents: 130000,
    stock: 20,
    volume: "750ml",
    weightG: 1420,
    widthMm: 82,
    heightMm: 318,
    lengthMm: 82,
  },
  {
    key: "wine-fr-030",
    name: "Baron de L Pouilly-Fumé",
    slug: "baron-de-l-pouilly-fume",
    categoryKey: "vinhos-brancos",
    categoryName: "Vinhos Brancos",
    brand: "De Ladoucette",
    origem: 1,
    country: "França",
    region: "Vallée de la Loire",
    grape: "Sauvignon Blanc",
    vintage: "2020",
    alcohol: "13.0%",
    color: "Branco",
    description: "Considerado por especialistas como a maior expressão do Sauvignon Blanc no planeta, elaborado nas melhores encostas do Loire.",
    priceCents: 125000,
    compareAtPriceCents: 145000,
    stock: 18,
    volume: "750ml",
    weightG: 1360,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-fr-031",
    name: "Château d'Esclans Whispering Angel Rosé",
    slug: "chateau-desclans-whispering-angel-rose",
    categoryKey: "vinhos-roses",
    categoryName: "Vinhos Rosés",
    brand: "Château d'Esclans",
    origem: 1,
    country: "França",
    region: "Provence",
    grape: "Grenache, Cinsault, Rolle",
    vintage: "2022",
    alcohol: "13.0%",
    color: "Rosé",
    description: "O rosé mais famoso e cobiçado de Provence, com coloração pálida, perfil aromático refinado e frescor encantador.",
    priceCents: 29000,
    compareAtPriceCents: 33000,
    stock: 40,
    volume: "750ml",
    weightG: 1340,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-fr-032",
    name: "Louis Latour Corton-Charlemagne Grand Cru",
    slug: "louis-latour-corton-charlemagne-grand-cru",
    categoryKey: "vinhos-brancos",
    categoryName: "Vinhos Brancos",
    brand: "Maison Louis Latour",
    origem: 1,
    country: "França",
    region: "Bourgogne - Côte de Beaune",
    grape: "Chardonnay",
    vintage: "2020",
    alcohol: "13.5%",
    color: "Branco",
    description: "Grand Cru reverenciado da colina de Corton com toques minerais nobres, avelãs tostadas e estrutura cremosa majestosa.",
    priceCents: 265000,
    compareAtPriceCents: 310000,
    stock: 12,
    volume: "750ml",
    weightG: 1380,
    widthMm: 80,
    heightMm: 312,
    lengthMm: 80,
  },

  // --- ITÁLIA (8) ---
  {
    key: "wine-it-033",
    name: "Sassicaia Tenuta San Guido",
    slug: "sassicaia-tenuta-san-guido",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Tenuta San Guido",
    origem: 1,
    country: "Itália",
    region: "Toscana - Bolgheri",
    grape: "Cabernet Sauvignon, Cabernet Franc",
    vintage: "2019",
    alcohol: "14.0%",
    color: "Tinto",
    description: "O criador do mito dos Supertoscanos em Bolgheri, reverenciado globalmente por sua aristocrática harmonia e potência.",
    priceCents: 380000,
    compareAtPriceCents: 430000,
    stock: 12,
    volume: "750ml",
    weightG: 1450,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-it-034",
    name: "Tignanello Marchesi Antinori",
    slug: "tignanello-marchesi-antinori",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Marchesi Antinori",
    origem: 1,
    country: "Itália",
    region: "Toscana",
    grape: "Sangiovese, Cabernet Sauvignon, Cabernet Franc",
    vintage: "2020",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Primeiro Sangiovese envelhecido em barricas pequenas e combinado com castas bordalesas na célebre colina de Tignanello.",
    priceCents: 175000,
    compareAtPriceCents: 199000,
    stock: 24,
    volume: "750ml",
    weightG: 1440,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-it-035",
    name: "Ornellaia Bolgheri Superiore",
    slug: "ornellaia-bolgheri-superiore",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Ornellaia",
    origem: 1,
    country: "Itália",
    region: "Toscana - Bolgheri",
    grape: "Cabernet Sauvignon, Merlot, Cabernet Franc",
    vintage: "2019",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Esculpido na costa toscana de Bolgheri, um blend suntuoso que une a opulência do Mediterrâneo à precisão artesanal.",
    priceCents: 320000,
    compareAtPriceCents: 365000,
    stock: 14,
    volume: "750ml",
    weightG: 1460,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-it-036",
    name: "Biondi-Santi Brunello di Montalcino",
    slug: "biondi-santi-brunello-di-montalcino",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Biondi-Santi Tenuta Greppo",
    origem: 1,
    country: "Itália",
    region: "Toscana - Montalcino",
    grape: "Sangiovese Grosso",
    vintage: "2016",
    alcohol: "13.5%",
    color: "Tinto",
    description: "O berço do Brunello di Montalcino na Tenuta Greppo, concebido para evoluir elegantemente ao longo de meio século.",
    priceCents: 245000,
    compareAtPriceCents: 280000,
    stock: 16,
    volume: "750ml",
    weightG: 1430,
    widthMm: 82,
    heightMm: 318,
    lengthMm: 82,
  },
  {
    key: "wine-it-037",
    name: "Barolo Fontanafredda Serralunga d'Alba",
    slug: "barolo-fontanafredda-serralunga-dalba",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Fontanafredda",
    origem: 1,
    country: "Itália",
    region: "Piemonte - Langhe",
    grape: "Nebbiolo",
    vintage: "2018",
    alcohol: "14.0%",
    color: "Tinto",
    description: "O rei dos vinhos e o vinho dos reis nascido na propriedade histórica do primeiro Rei da Itália, Victor Emmanuel II.",
    priceCents: 59000,
    compareAtPriceCents: 68000,
    stock: 30,
    volume: "750ml",
    weightG: 1390,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-it-038",
    name: "Tommasi Amarone della Valpolicella Classico",
    slug: "tommasi-amarone-della-valpolicella-classico",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Tommasi Viticoltori",
    origem: 1,
    country: "Itália",
    region: "Veneto - Valpolicella",
    grape: "Corvina, Rondinella, Molinara",
    vintage: "2017",
    alcohol: "15.0%",
    color: "Tinto",
    description: "Produzido com uvas desidratadas pelo método appassimento durante 100 dias, resultando em corpo aveludado e notas de cereja madura.",
    priceCents: 78000,
    compareAtPriceCents: 89000,
    stock: 24,
    volume: "750ml",
    weightG: 1450,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-it-039",
    name: "Gaja Barbaresco",
    slug: "gaja-barbaresco",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Gaja",
    origem: 1,
    country: "Itália",
    region: "Piemonte - Barbaresco",
    grape: "Nebbiolo",
    vintage: "2019",
    alcohol: "14.0%",
    color: "Tinto",
    description: "O vinho que revolucionou o Piemonte pela visão pioneira de Angelo Gaja, combinando poder tânico com elegância sedutora.",
    priceCents: 360000,
    compareAtPriceCents: 410000,
    stock: 12,
    volume: "750ml",
    weightG: 1440,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-it-040",
    name: "Santa Cristina Chianti Superiore",
    slug: "santa-cristina-chianti-superiore",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Santa Cristina",
    origem: 1,
    country: "Itália",
    region: "Toscana",
    grape: "Sangiovese, Merlot",
    vintage: "2021",
    alcohol: "13.0%",
    color: "Tinto",
    description: "Clássico toscano acessível e gastronômico, com notas de violeta, frutas vermelhas frescas e acidez vibrante.",
    priceCents: 13900,
    compareAtPriceCents: 16500,
    stock: 60,
    volume: "750ml",
    weightG: 1350,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },

  // --- PORTUGAL (6) ---
  {
    key: "wine-pt-041",
    name: "Barca Velha Casa Ferreirinha",
    slug: "barca-velha-casa-ferreirinha",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Casa Ferreirinha",
    origem: 1,
    country: "Portugal",
    region: "Douro",
    grape: "Touriga Franca, Touriga Nacional, Tinta Roriz",
    vintage: "2011",
    alcohol: "14.5%",
    color: "Tinto",
    description: "O vinho mais mítico de Portugal, lançado exclusivamente em safras lendárias após uma década de repouso em adega.",
    priceCents: 750000,
    compareAtPriceCents: 850000,
    stock: 8,
    volume: "750ml",
    weightG: 1460,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-pt-042",
    name: "Quinta do Crasto Reserva Vinhas Velhas",
    slug: "quinta-do-crasto-reserva-vinhas-velhas",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Quinta do Crasto",
    origem: 1,
    country: "Portugal",
    region: "Douro",
    grape: "Vinhas Velhas - Field Blend",
    vintage: "2019",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Field blend com mais de 30 variedades autóctones de vinhedos centenários encravados nos socalcos xistosos do Douro.",
    priceCents: 58000,
    compareAtPriceCents: 66000,
    stock: 36,
    volume: "750ml",
    weightG: 1380,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-pt-043",
    name: "Taylor's Vintage Port 2017",
    slug: "taylors-vintage-port-2017",
    categoryKey: "vinhos-sobremesa-fortificados",
    categoryName: "Vinhos de Sobremesa & Fortificados",
    brand: "The Fladgate Partnership",
    origem: 1,
    country: "Portugal",
    region: "Douro - Porto",
    grape: "Touriga Nacional, Touriga Franca",
    vintage: "2017",
    alcohol: "20.0%",
    color: "Sobremesa",
    description: "Safra declarada histórica de Vinho do Porto, aclamada universalmente com 100 pontos pela crítica internacional.",
    priceCents: 155000,
    compareAtPriceCents: 180000,
    stock: 20,
    volume: "750ml",
    weightG: 1480,
    widthMm: 82,
    heightMm: 315,
    lengthMm: 82,
  },
  {
    key: "wine-pt-044",
    name: "Cartuxa Pêra-Manca Tinto",
    slug: "cartuxa-pera-manca-tinto",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Fundação Eugénio de Almeida",
    origem: 1,
    country: "Portugal",
    region: "Alentejo - Évora",
    grape: "Trincadeira, Aragonez",
    vintage: "2015",
    alcohol: "14.5%",
    color: "Tinto",
    description: "Ícone sagrado do Alentejo com séculos de prestígio, estagiando 18 meses em balseiros de carvalho francês e 36 meses em garrafa.",
    priceCents: 420000,
    compareAtPriceCents: 490000,
    stock: 10,
    volume: "750ml",
    weightG: 1480,
    widthMm: 82,
    heightMm: 322,
    lengthMm: 82,
  },
  {
    key: "wine-pt-045",
    name: "Esporão Reserva Tinto",
    slug: "esporao-reserva-tinto",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Herdade do Esporão",
    origem: 1,
    country: "Portugal",
    region: "Alentejo - Reguengos",
    grape: "Aragonez, Trincadeira, Alicante Bouschet",
    vintage: "2020",
    alcohol: "14.5%",
    color: "Tinto",
    description: "O pioneiro de Reguengos de Monsaraz que consagrou a cultura do vinho alentejano moderno, ilustrado anualmente por artistas plásticos.",
    priceCents: 23900,
    compareAtPriceCents: 27500,
    stock: 50,
    volume: "750ml",
    weightG: 1360,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-pt-046",
    name: "Quinta do Noval Nacional Vintage Port",
    slug: "quinta-do-noval-nacional-vintage-port",
    categoryKey: "vinhos-sobremesa-fortificados",
    categoryName: "Vinhos de Sobremesa & Fortificados",
    brand: "Quinta do Noval",
    origem: 1,
    country: "Portugal",
    region: "Douro - Porto",
    grape: "Touriga Nacional, Tinta Roriz",
    vintage: "2016",
    alcohol: "19.5%",
    color: "Sobremesa",
    description: "Produzido a partir de um pequeno lote de videiras em pé-franco não enxertadas que sobreviveram milagrosamente à filoxera.",
    priceCents: 890000,
    compareAtPriceCents: 990000,
    stock: 4,
    volume: "750ml",
    weightG: 1500,
    widthMm: 84,
    heightMm: 320,
    lengthMm: 84,
  },

  // --- ESPANHA (4) ---
  {
    key: "wine-es-047",
    name: "Vega Sicilia Único",
    slug: "vega-sicilia-unico",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Tempos Vega Sicilia",
    origem: 1,
    country: "Espanha",
    region: "Ribera del Duero",
    grape: "Tempranillo, Cabernet Sauvignon",
    vintage: "2012",
    alcohol: "14.0%",
    color: "Tinto",
    description: "O patriarca dos grandes vinhos espanhóis, amadurecido por quase 10 anos entre barricas e garrafa antes de ser colocado no mercado.",
    priceCents: 590000,
    compareAtPriceCents: 680000,
    stock: 10,
    volume: "750ml",
    weightG: 1460,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
  {
    key: "wine-es-048",
    name: "Marqués de Riscal Reserva",
    slug: "marques-de-riscal-reserva",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Herederos del Marqués de Riscal",
    origem: 1,
    country: "Espanha",
    region: "Rioja",
    grape: "Tempranillo, Graciano",
    vintage: "2018",
    alcohol: "14.0%",
    color: "Tinto",
    description: "Clássico atemporal da Rioja protegido pela famosa malha de arame dourado, com 24 meses em barricas de carvalho americano.",
    priceCents: 25900,
    compareAtPriceCents: 29900,
    stock: 48,
    volume: "750ml",
    weightG: 1360,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-es-049",
    name: "Tinto Pesquera Crianza",
    slug: "tinto-pesquera-crianza",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Familia Fernández Rivera",
    origem: 1,
    country: "Espanha",
    region: "Ribera del Duero",
    grape: "Tempranillo",
    vintage: "2019",
    alcohol: "14.5%",
    color: "Tinto",
    description: "O vinho que colocou Ribera del Duero no mapa pelas mãos do mestre Alejandro Fernández, apelidado de Petrus da Espanha por Robert Parker.",
    priceCents: 36000,
    compareAtPriceCents: 41000,
    stock: 36,
    volume: "750ml",
    weightG: 1380,
    widthMm: 80,
    heightMm: 315,
    lengthMm: 80,
  },
  {
    key: "wine-es-050",
    name: "Dominio de Pingus Pingus",
    slug: "dominio-de-pingus-pingus",
    categoryKey: "vinhos-tintos",
    categoryName: "Vinhos Tintos",
    brand: "Dominio de Pingus",
    origem: 1,
    country: "Espanha",
    region: "Ribera del Duero",
    grape: "Tempranillo",
    vintage: "2019",
    alcohol: "14.5%",
    color: "Tinto",
    description: "O vinho cult supremo de Peter Sisseck produzido com parcelas microscópicas de vinhas muito velhas de cultivo biodinâmico rigoroso.",
    priceCents: 980000,
    compareAtPriceCents: 1150000,
    stock: 4,
    volume: "750ml",
    weightG: 1480,
    widthMm: 82,
    heightMm: 320,
    lengthMm: 82,
  },
];

const csvEscape = (value) => {
  const text = value == null ? "" : String(value);
  return /[",\n\r]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
};

const rows = realWines.map((wine, index) => {
  const seq = String(index + 1).padStart(3, "0");
  const code = `WINE-${seq}-${wine.volume.replace("ml", "")}`;
  const skuKey = `${wine.key}-${wine.volume.toLowerCase()}`;

  return {
    entity_type: "sku",
    product_key: wine.key,
    sku_key: skuKey,
    category_key: wine.categoryKey,
    category_name: wine.categoryName,
    product_name: wine.name,
    slug: wine.slug,
    description: wine.description,
    brand: wine.brand,
    ncm: "22042100",
    cest: "0301200",
    origem_mercadoria: wine.origem,
    code: code,
    variant_key: wine.volume,
    price_cents: wine.priceCents,
    compare_at_price_cents: wine.compareAtPriceCents,
    stock_quantity: wine.stock,
    weight_g: wine.weightG,
    width_mm: wine.widthMm,
    height_mm: wine.heightMm,
    length_mm: wine.lengthMm,
    active: true,
    country: wine.country,
    region: wine.region,
    grape: wine.grape,
    vintage: wine.vintage,
    alcohol: wine.alcohol,
    volume: wine.volume,
    color: wine.color,
  };
});

const headers = Object.keys(rows[0]);
const csvLines = [
  headers.join(","),
  ...rows.map((row) => headers.map((key) => csvEscape(row[key])).join(",")),
];
const csvContent = `${csvLines.join("\n")}\n`;
const csvPath = path.join(outDir, "wine_catalog.csv");

fs.writeFileSync(csvPath, csvContent, "utf-8");
console.log(`Successfully wrote ${rows.length} real wines to ${csvPath}`);
