pub mod authentication_routes;
pub mod cart_routes;
pub mod customer_routes;
pub mod marketing_routes;
pub mod order_routes;
pub mod resource_routes;
pub mod shipping_tax_routes;
pub mod tenant_routes;
pub mod user_routes;
